os:
  - linux
  - osx
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    packages:
    - libjsoncpp-dev
    - uuid-dev
    - zlib1g-dev
    - postgresql-server-dev-10
    - openssl
    - libssl-dev
    - build-essential
    - cmake
  homebrew:
    packages:
    - openssl
    - cmake
    - libtool
    - lz4
    - postgresql

script:
  - ./build.sh


